# Reorder import and extern crate statements alphabetically in groups (a group is separated by a newline).
reorder_imports = true

# Maximum width of a line
max_width = 100

# Break comments to fit on the line.
wrap_comments = true

# Replace strings of `_` wildcards by a single `.` In tuple patterns.
condense_wildcard_suffixes = true

# Error if Rustfmt is unable to get all lines within max_width, except for comments and string literals.
error_on_line_overflow = false

# Format code snippet included in doc comments.
format_code_in_doc_comments = true

# Convert /* */ comments to // comments where possible.
normalize_comments = true

# Convert #![doc] and #[doc] attributes to //! and /// doc comments.
normalize_doc_attributes = true

# Merge imports from the same crate into a single use statement.
# Conversely, imports from different crates are split into separate statements.
imports_granularity = "Crate"

# Discard existing import groups, and create three groups for:
# std, core and alloc,
# external crates,
# self, super and crate imports.
group_imports = "StdExternalCrate"